import React from 'react';
import { data, normalizeList } from '../lib/data.js';
import { ErrorNotice, PageHeading, Skeleton } from '../components/Shell.jsx';

function useSection(loader, refreshKey) { const [value, setValue] = React.useState(null); const [error, setError] = React.useState(''); const [loading, setLoading] = React.useState(true); React.useEffect(() => { let live = true; setLoading(true); setError(''); loader().then(result => { if (live) setValue(normalizeList(result)); }).catch(err => { if (live) setError(err.message); }).finally(() => { if (live) setLoading(false); }); return () => { live = false; }; }, [loader, refreshKey]); return { value: value || [], error, loading }; }
export default function HrPage() {
  const [refreshKey, setRefreshKey] = React.useState(0); const loadGaps = React.useCallback(() => data.getHrSkillGaps(), []); const loadPeople = React.useCallback(() => data.getHrEmployeesWithoutRecommendation(), []); const loadStats = React.useCallback(() => data.getHrParticipationStats(), []);
  const gaps = useSection(loadGaps, refreshKey), people = useSection(loadPeople, refreshKey), stats = useSection(loadStats, refreshKey);
  const maxGap = Math.max(1, ...gaps.value.map(x => Number(x.total_gap || 0)));
  return <div className="page-wrap"><PageHeading eyebrow="PEOPLE INSIGHTS" title="Grow the whole team." subtitle="Spot development needs across the organization and make the next conversation count." action={<button className="button-secondary" onClick={() => setRefreshKey(k => k + 1)}><span className="refresh-icon">↻</span> Refresh data</button>}/>
    <div className="hr-grid">
      <section className="panel hr-panel gaps-panel"><div className="section-heading"><div><div className="eyebrow">CAPABILITY OVERVIEW</div><h2>Skill gaps across the company</h2></div><span className="small-count">TOP 15</span></div><p className="muted">Combined gap score and number of people affected.</p><ErrorNotice message={gaps.error}/>{gaps.loading ? <Skeleton rows={5}/> : <div className="gap-list">{gaps.value.slice().sort((a,b) => b.total_gap - a.total_gap).slice(0, 15).map((gap, i) => <div className="gap-row" key={gap.skill_id || i}><div className="gap-label"><span className="rank-index">{String(i + 1).padStart(2, '0')}</span><strong>{gap.skill_name || gap.skill_id}</strong><small>{gap.employees_affected} people</small></div><div className="gap-meter"><i style={{ width: `${Math.max(4, Number(gap.total_gap || 0) / maxGap * 100)}%` }}/></div><b className="gap-number">{gap.total_gap}</b></div>)}</div>}</section>
      <section className="panel hr-panel people-panel"><div className="section-heading"><div><div className="eyebrow">PERSONALIZED FOLLOW-UP</div><h2>Employees without a next step</h2></div><span className="people-count">{people.value.length}</span></div><p className="muted">These employees are either at the top grade or have no eligible activity right now — may need a manual check-in.</p><ErrorNotice message={people.error}/>{people.loading ? <Skeleton rows={4}/> : <div className="people-list">{people.value.map(person => <a className="person-row" href={`/employee/${encodeURIComponent(person.employee_id)}`} key={person.employee_id}><span className="person-avatar">{person.full_name?.split(/\s+/).map(s => s[0]).slice(0, 2).join('')}</span><span className="person-details"><strong>{person.full_name}</strong><small>{person.role}</small></span><span className="grade-badge">{person.grade}</span><span className="row-arrow">↗</span></a>)}</div>}</section>
    </div>
    <section className="panel hr-panel participation-panel"><div className="section-heading"><div><div className="eyebrow">LEARNING ENGAGEMENT</div><h2>Participation by activity</h2></div><div className="legend"><span><i className="legend-completed"/>Completed</span><span><i className="legend-inprogress"/>In progress</span><span><i className="legend-dropped"/>Dropped</span><span><i className="legend-declined"/>Declined / no-show</span></div></div><ErrorNotice message={stats.error}/>{stats.loading ? <Skeleton rows={4}/> : <div className="participation-table"><div className="participation-header"><span>ACTIVITY</span><span>COMPLETED</span><span>DECLINED</span><span>NO-SHOW</span><span>DROPPED</span><span>IN PROGRESS</span></div>{stats.value.map((row, index) => { const values = [['completed', 'legend-completed'], ['in_progress', 'legend-inprogress'], ['dropped', 'legend-dropped'], ['declined', 'legend-declined'], ['no_show', 'legend-noshow']]; const total = values.reduce((sum, [key]) => sum + Number(row[key] || 0), 0) || 1; return <div className="participation-row" key={row.event_id || index}><strong>{row.title || row.event_title || row.event_id}</strong>{values.map(([key]) => <span key={key}>{row[key] || 0}</span>)}<div className="stacked-bar" aria-label={`Activity status distribution for ${row.title || row.event_id}`}>{values.map(([key, klass]) => <i key={key} className={klass} style={{ width: `${Number(row[key] || 0) / total * 100}%` }}/>)}</div></div>; })}</div>}</section>
  </div>;
}
